# Generated by Django 5.2.7 on 2025-11-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takip_no', models.CharField(max_length=15, unique=True, verbose_name='Takip Numarası')),
                ('alici_isim', models.CharField(max_length=100, verbose_name='Alıcı Adı Soyadı')),
                ('alici_adres', models.TextField(verbose_name='Teslimat Adresi')),
                ('durum', models.CharField(choices=[('HAZIRLANIYOR', 'Sipariş Hazırlanıyor'), ('YOLDA', 'Kargo Yolda (Transfer Merkezi)'), ('DAGITIMDA', 'Dağıtıma Çıktı'), ('TESLIM', 'Teslim Edildi'), ('IPTAL', 'İptal Edildi')], default='HAZIRLANIYOR', max_length=15, verbose_name='Kargo Durumu')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Kargo Ücreti')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kargo Gönderisi',
                'verbose_name_plural': 'Kargo Gönderileri',
            },
        ),
    ]
